/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t.shirt.shop.client;

/**
 *
 * @author marlon.rosendahl
 */
public class Home extends javax.swing.JFrame {

    ClientController ctrl;
    
    public Home(ClientController ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTop10_1 = new javax.swing.JPanel();
        ltop10_1 = new javax.swing.JLabel();
        pTop10_2 = new javax.swing.JPanel();
        ltop10_2 = new javax.swing.JLabel();
        pTop10_3 = new javax.swing.JPanel();
        ltop10_3 = new javax.swing.JLabel();
        pTop10_4 = new javax.swing.JPanel();
        ltop10_4 = new javax.swing.JLabel();
        pTop10_5 = new javax.swing.JPanel();
        ltop10_5 = new javax.swing.JLabel();
        pTop10_6 = new javax.swing.JPanel();
        ltop10_6 = new javax.swing.JLabel();
        pTop10_7 = new javax.swing.JPanel();
        ltop10_7 = new javax.swing.JLabel();
        pTop10_8 = new javax.swing.JPanel();
        ltop10_8 = new javax.swing.JLabel();
        pTop10_9 = new javax.swing.JPanel();
        ltop10_9 = new javax.swing.JLabel();
        pTop10_10 = new javax.swing.JPanel();
        ltop10_10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Home = new javax.swing.JMenu();
        Menu_Warenkorb = new javax.swing.JMenu();
        Menu_LoginLogout = new javax.swing.JMenu();
        Menu_Produkt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pTop10_1.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_1MouseClicked(evt);
            }
        });

        ltop10_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_1.setText("1");
        ltop10_1.setAlignmentY(0.0F);

        javax.swing.GroupLayout pTop10_1Layout = new javax.swing.GroupLayout(pTop10_1);
        pTop10_1.setLayout(pTop10_1Layout);
        pTop10_1Layout.setHorizontalGroup(
            pTop10_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pTop10_1Layout.setVerticalGroup(
            pTop10_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_2.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_2MouseClicked(evt);
            }
        });

        ltop10_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_2.setText("2");

        javax.swing.GroupLayout pTop10_2Layout = new javax.swing.GroupLayout(pTop10_2);
        pTop10_2.setLayout(pTop10_2Layout);
        pTop10_2Layout.setHorizontalGroup(
            pTop10_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pTop10_2Layout.setVerticalGroup(
            pTop10_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_3.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_3MouseClicked(evt);
            }
        });

        ltop10_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_3.setText("3");

        javax.swing.GroupLayout pTop10_3Layout = new javax.swing.GroupLayout(pTop10_3);
        pTop10_3.setLayout(pTop10_3Layout);
        pTop10_3Layout.setHorizontalGroup(
            pTop10_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pTop10_3Layout.setVerticalGroup(
            pTop10_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_4.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_4MouseClicked(evt);
            }
        });

        ltop10_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_4.setText("4");

        javax.swing.GroupLayout pTop10_4Layout = new javax.swing.GroupLayout(pTop10_4);
        pTop10_4.setLayout(pTop10_4Layout);
        pTop10_4Layout.setHorizontalGroup(
            pTop10_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pTop10_4Layout.setVerticalGroup(
            pTop10_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_5.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_5MouseClicked(evt);
            }
        });

        ltop10_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_5.setText("5");

        javax.swing.GroupLayout pTop10_5Layout = new javax.swing.GroupLayout(pTop10_5);
        pTop10_5.setLayout(pTop10_5Layout);
        pTop10_5Layout.setHorizontalGroup(
            pTop10_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pTop10_5Layout.setVerticalGroup(
            pTop10_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_6.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_6MouseClicked(evt);
            }
        });

        ltop10_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_6.setText("6");

        javax.swing.GroupLayout pTop10_6Layout = new javax.swing.GroupLayout(pTop10_6);
        pTop10_6.setLayout(pTop10_6Layout);
        pTop10_6Layout.setHorizontalGroup(
            pTop10_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pTop10_6Layout.setVerticalGroup(
            pTop10_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_7.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_7MouseClicked(evt);
            }
        });

        ltop10_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_7.setText("7");

        javax.swing.GroupLayout pTop10_7Layout = new javax.swing.GroupLayout(pTop10_7);
        pTop10_7.setLayout(pTop10_7Layout);
        pTop10_7Layout.setHorizontalGroup(
            pTop10_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTop10_7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ltop10_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pTop10_7Layout.setVerticalGroup(
            pTop10_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_8.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_8MouseClicked(evt);
            }
        });

        ltop10_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_8.setText("8");

        javax.swing.GroupLayout pTop10_8Layout = new javax.swing.GroupLayout(pTop10_8);
        pTop10_8.setLayout(pTop10_8Layout);
        pTop10_8Layout.setHorizontalGroup(
            pTop10_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTop10_8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ltop10_8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pTop10_8Layout.setVerticalGroup(
            pTop10_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_9.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_9MouseClicked(evt);
            }
        });

        ltop10_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_9.setText("9");

        javax.swing.GroupLayout pTop10_9Layout = new javax.swing.GroupLayout(pTop10_9);
        pTop10_9.setLayout(pTop10_9Layout);
        pTop10_9Layout.setHorizontalGroup(
            pTop10_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTop10_9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ltop10_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pTop10_9Layout.setVerticalGroup(
            pTop10_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pTop10_10.setMaximumSize(new java.awt.Dimension(100, 100));
        pTop10_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTop10_10MouseClicked(evt);
            }
        });

        ltop10_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltop10_10.setText("10");

        javax.swing.GroupLayout pTop10_10Layout = new javax.swing.GroupLayout(pTop10_10);
        pTop10_10.setLayout(pTop10_10Layout);
        pTop10_10Layout.setHorizontalGroup(
            pTop10_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTop10_10Layout.createSequentialGroup()
                .addComponent(ltop10_10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pTop10_10Layout.setVerticalGroup(
            pTop10_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ltop10_10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Home);

        Menu_Warenkorb.setText("Warenkorb");
        Menu_Warenkorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_WarenkorbMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Warenkorb);

        Menu_LoginLogout.setText("Login/Logout");
        Menu_LoginLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_LoginLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_LoginLogout);

        Menu_Produkt.setText("Produkt");
        Menu_Produkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ProduktMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Produkt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTop10_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTop10_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTop10_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pTop10_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTop10_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTop10_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTop10_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTop10_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pTop10_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pTop10_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pTop10_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pTop10_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pTop10_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
        this.ctrl.showFrame("home");
       
    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_WarenkorbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_WarenkorbMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("warenkorb");
    }//GEN-LAST:event_Menu_WarenkorbMouseClicked

    private void Menu_LoginLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_LoginLogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("loginLogout");
    }//GEN-LAST:event_Menu_LoginLogoutMouseClicked

    private void pTop10_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_1MouseClicked

    private void pTop10_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_2MouseClicked

    private void pTop10_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_3MouseClicked

    private void pTop10_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_4MouseClicked

    private void pTop10_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_5MouseClicked

    private void pTop10_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_6MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_6MouseClicked

    private void pTop10_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_7MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_7MouseClicked

    private void pTop10_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_8MouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_8MouseClicked

    private void pTop10_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_9MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_9MouseClicked

    private void pTop10_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTop10_10MouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_pTop10_10MouseClicked

    private void Menu_ProduktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ProduktMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_Menu_ProduktMouseClicked
 
     
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Home;
    private javax.swing.JMenu Menu_LoginLogout;
    private javax.swing.JMenu Menu_Produkt;
    private javax.swing.JMenu Menu_Warenkorb;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel ltop10_1;
    private javax.swing.JLabel ltop10_10;
    private javax.swing.JLabel ltop10_2;
    private javax.swing.JLabel ltop10_3;
    private javax.swing.JLabel ltop10_4;
    private javax.swing.JLabel ltop10_5;
    private javax.swing.JLabel ltop10_6;
    private javax.swing.JLabel ltop10_7;
    private javax.swing.JLabel ltop10_8;
    private javax.swing.JLabel ltop10_9;
    private javax.swing.JPanel pTop10_1;
    private javax.swing.JPanel pTop10_10;
    private javax.swing.JPanel pTop10_2;
    private javax.swing.JPanel pTop10_3;
    private javax.swing.JPanel pTop10_4;
    private javax.swing.JPanel pTop10_5;
    private javax.swing.JPanel pTop10_6;
    private javax.swing.JPanel pTop10_7;
    private javax.swing.JPanel pTop10_8;
    private javax.swing.JPanel pTop10_9;
    // End of variables declaration//GEN-END:variables

   
 
}
