/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t.shirt.shop.client;

/**
 *
 * @author marlon.rosendahl
 */
public class LoginLogout extends javax.swing.JFrame {


    ClientController ctrl;
    
    public LoginLogout(ClientController ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_Logout_Logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Home = new javax.swing.JMenu();
        Menu_Warenkorb = new javax.swing.JMenu();
        Menu_LoginLogout = new javax.swing.JMenu();
        Menu_Produkt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        b_Logout_Logout.setText("AUSLOGGEN");
        b_Logout_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Logout_LogoutMouseClicked(evt);
            }
        });

        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Home);

        Menu_Warenkorb.setText("Warenkorb");
        Menu_Warenkorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_WarenkorbMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Warenkorb);

        Menu_LoginLogout.setText("Login/Logout");
        Menu_LoginLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_LoginLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_LoginLogout);

        Menu_Produkt.setText("Produkt");
        Menu_Produkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ProduktMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Produkt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(b_Logout_Logout)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(b_Logout_Logout)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked
        // TODO add your handling code here:
     this.setVisible(false);
        this.ctrl.showFrame("home");
    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_WarenkorbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_WarenkorbMouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
        this.ctrl.showFrame("warenkorb");
    }//GEN-LAST:event_Menu_WarenkorbMouseClicked

    private void Menu_LoginLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_LoginLogoutMouseClicked
        // TODO add your handling code here:
             this.setVisible(false);
        this.ctrl.showFrame("loginLogout");
        
    }//GEN-LAST:event_Menu_LoginLogoutMouseClicked

    private void Menu_ProduktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ProduktMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_Menu_ProduktMouseClicked

    private void b_Logout_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Logout_LogoutMouseClicked
        // TODO add your handling code here:
        LoginLogout.getFrames();
        this.dispose();
    }//GEN-LAST:event_b_Logout_LogoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Home;
    private javax.swing.JMenu Menu_LoginLogout;
    private javax.swing.JMenu Menu_Produkt;
    private javax.swing.JMenu Menu_Warenkorb;
    private javax.swing.JButton b_Logout_Logout;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
