/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t.shirt.shop.client;

public class Produktänderung extends javax.swing.JFrame {
      ClientController ctrl;

    /**
     * Creates new form Produktänderung
     */
    public Produktänderung(ClientController ctrl) {
        initComponents();
         this.ctrl = ctrl;
         jC_PrÄnderung_Farbe.addItem("Farbe 1");
         jC_PrÄnderung_Farbe.addItem("Farbe 2");
         jC_PrÄnderung_Farbe.addItem("Farbe 3");
         jC_PrÄnderung_Farbe.addItem("Farbe 4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPrÄnderung_Warenkorb = new javax.swing.JButton();
        jC_PrÄnderung_Farbe = new javax.swing.JComboBox<>();
        jC_PrÄnderung_Groesse = new javax.swing.JComboBox<>();
        jC_PrÄnderung_Anzahl = new javax.swing.JComboBox<>();
        LBild_PrÄnderung_Bild = new javax.swing.JLabel();
        l_Produktänderung_Produktname = new javax.swing.JLabel();
        l_Produktänderung_Preis = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Home = new javax.swing.JMenu();
        Menu_Warenkorb = new javax.swing.JMenu();
        Menu_LoginLogout = new javax.swing.JMenu();
        Menu_Produkt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        bPrÄnderung_Warenkorb.setText("In den Warenkorb");
        bPrÄnderung_Warenkorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPrÄnderung_WarenkorbMouseClicked(evt);
            }
        });

        jC_PrÄnderung_Groesse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jC_PrÄnderung_Anzahl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LBild_PrÄnderung_Bild.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBild_PrÄnderung_Bild.setText("Bild");

        l_Produktänderung_Produktname.setText("Produktname");

        l_Produktänderung_Preis.setText("Preis");

        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Home);

        Menu_Warenkorb.setText("Warenkorb");
        Menu_Warenkorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_WarenkorbMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Warenkorb);

        Menu_LoginLogout.setText("Login/Logout");
        Menu_LoginLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_LoginLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_LoginLogout);

        Menu_Produkt.setText("Produkt");
        Menu_Produkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ProduktMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Produkt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBild_PrÄnderung_Bild, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_Produktänderung_Preis)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bPrÄnderung_Warenkorb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jC_PrÄnderung_Anzahl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jC_PrÄnderung_Groesse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jC_PrÄnderung_Farbe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(l_Produktänderung_Produktname)
                                .addGap(39, 39, 39)))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBild_PrÄnderung_Bild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(l_Produktänderung_Produktname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(jC_PrÄnderung_Farbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_PrÄnderung_Groesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_PrÄnderung_Anzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(l_Produktänderung_Preis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bPrÄnderung_Warenkorb)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("home");

    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_WarenkorbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_WarenkorbMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("warenkorb");
    }//GEN-LAST:event_Menu_WarenkorbMouseClicked

    private void Menu_LoginLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_LoginLogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("loginLogout");
    }//GEN-LAST:event_Menu_LoginLogoutMouseClicked

    private void Menu_ProduktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ProduktMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_Menu_ProduktMouseClicked

    private void bPrÄnderung_WarenkorbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPrÄnderung_WarenkorbMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("warenkorb");
        
    }//GEN-LAST:event_bPrÄnderung_WarenkorbMouseClicked
   
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBild_PrÄnderung_Bild;
    private javax.swing.JMenu Menu_Home;
    private javax.swing.JMenu Menu_LoginLogout;
    private javax.swing.JMenu Menu_Produkt;
    private javax.swing.JMenu Menu_Warenkorb;
    private javax.swing.JButton bPrÄnderung_Warenkorb;
    private javax.swing.JComboBox<String> jC_PrÄnderung_Anzahl;
    private javax.swing.JComboBox<String> jC_PrÄnderung_Farbe;
    private javax.swing.JComboBox<String> jC_PrÄnderung_Groesse;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel l_Produktänderung_Preis;
    private javax.swing.JLabel l_Produktänderung_Produktname;
    // End of variables declaration//GEN-END:variables
}
