/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t.shirt.shop.client;

/**
 *
 * @author marlon.rosendahl
 */
public class VielenDank extends javax.swing.JFrame {

    
     ClientController ctrl;
     
    public VielenDank(ClientController ctrl) {
        initComponents();
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_VielenDank_Text = new javax.swing.JLabel();
        b_VielenDanke_Weiter = new javax.swing.JButton();
        b_VielenDank_Ausloggen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l_VielenDank_Text.setText("Vielen Dank für ihren Einkauf!");

        b_VielenDanke_Weiter.setText("Weiter Einkaufen");
        b_VielenDanke_Weiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_VielenDanke_WeiterMouseClicked(evt);
            }
        });

        b_VielenDank_Ausloggen.setText("Ausloggen");
        b_VielenDank_Ausloggen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_VielenDank_AusloggenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(l_VielenDank_Text))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(b_VielenDanke_Weiter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_VielenDank_Ausloggen)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(l_VielenDank_Text)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_VielenDanke_Weiter)
                    .addComponent(b_VielenDank_Ausloggen))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_VielenDank_AusloggenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_VielenDank_AusloggenMouseClicked
        // TODO add your handling code here:
        VielenDank.getFrames();
        this.dispose();
    }//GEN-LAST:event_b_VielenDank_AusloggenMouseClicked

    private void b_VielenDanke_WeiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_VielenDanke_WeiterMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        this.ctrl.showFrame("home");
    }//GEN-LAST:event_b_VielenDanke_WeiterMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_VielenDank_Ausloggen;
    private javax.swing.JButton b_VielenDanke_Weiter;
    private javax.swing.JLabel l_VielenDank_Text;
    // End of variables declaration//GEN-END:variables
}
