/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t.shirt.shop.client;

/**
 *
 * @author marlon.rosendahl
 */
public class Warenkorb extends javax.swing.JFrame {


    ClientController ctrl;
    
    public Warenkorb(ClientController ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        l_Warenkorb_Artikel = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        l_Warenkorb_Groesse = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        l_Warenkorb_PreisEinzeln = new javax.swing.JList<>();
        l_Warenkorb_PreisGesamt = new javax.swing.JLabel();
        b_Warenkorb_Bezahlen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Home = new javax.swing.JMenu();
        Menu_Warenkorb = new javax.swing.JMenu();
        Menu_LoginLogout = new javax.swing.JMenu();
        Menu_Produkt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l_Warenkorb_Artikel.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(l_Warenkorb_Artikel);

        l_Warenkorb_Groesse.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(l_Warenkorb_Groesse);

        l_Warenkorb_PreisEinzeln.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(l_Warenkorb_PreisEinzeln);

        l_Warenkorb_PreisGesamt.setText("Preis");

        b_Warenkorb_Bezahlen.setText("Bezahlen");
        b_Warenkorb_Bezahlen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Warenkorb_BezahlenMouseClicked(evt);
            }
        });

        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Home);

        Menu_Warenkorb.setText("Warenkorb");
        Menu_Warenkorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_WarenkorbMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Warenkorb);

        Menu_LoginLogout.setText("Login/Logout");
        Menu_LoginLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_LoginLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_LoginLogout);

        Menu_Produkt.setText("Produkt");
        Menu_Produkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ProduktMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Produkt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(l_Warenkorb_PreisGesamt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(b_Warenkorb_Bezahlen)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(l_Warenkorb_PreisGesamt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_Warenkorb_Bezahlen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
        this.ctrl.showFrame("home");
    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_WarenkorbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_WarenkorbMouseClicked
        // TODO add your handling code here:
           this.setVisible(false);
        this.ctrl.showFrame("warenkorb");
      
    }//GEN-LAST:event_Menu_WarenkorbMouseClicked

    private void Menu_LoginLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_LoginLogoutMouseClicked
        // TODO add your handling code here:
           this.setVisible(false);
        this.ctrl.showFrame("loginLogout");
    }//GEN-LAST:event_Menu_LoginLogoutMouseClicked

    private void Menu_ProduktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ProduktMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.ctrl.showFrame("produktänderung");
    }//GEN-LAST:event_Menu_ProduktMouseClicked

    private void b_Warenkorb_BezahlenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Warenkorb_BezahlenMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        this.ctrl.showFrame("vielendank");
    }//GEN-LAST:event_b_Warenkorb_BezahlenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Home;
    private javax.swing.JMenu Menu_LoginLogout;
    private javax.swing.JMenu Menu_Produkt;
    private javax.swing.JMenu Menu_Warenkorb;
    private javax.swing.JButton b_Warenkorb_Bezahlen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> l_Warenkorb_Artikel;
    private javax.swing.JList<String> l_Warenkorb_Groesse;
    private javax.swing.JList<String> l_Warenkorb_PreisEinzeln;
    private javax.swing.JLabel l_Warenkorb_PreisGesamt;
    // End of variables declaration//GEN-END:variables
}
